### ISSUE TITLE
Please add a new paper

### ISSUE THREAD

**Issue by BinhuiXie** [52CV/CVPR-2022-Papers#1]
Hello, @52CV 

We request to add our new work RIPU to this awesome repo.

Title: Towards Fewer Annotations: Active Learning via Region Impurity and Prediction Uncertainty for Domain Adaptive Semantic Segmentation

paper: https://arxiv.org/pdf/2111.12940.pdf
code: https://github.com/BIT-DA/RIPU

Thank you!

**Comment by 52CV** [comment]
thanks！
